### ISSUE TITLE
SSL broken - Application run and Tests

### ISSUE THREAD

**Issue by lfdesousa** [swisspost/MobileAccessGateway#5]
Hi,
I noticed, that in the current state we cannot have ssl tunred on both for tests, but also for running the MAG.

Workaround is to disable SSL in the files:

- application.yml
- application-test.yml

If you try to run tests with SSL enabled or if you try to run the MAG with SSL enabled you will get an error and the component will not start.

Below a sample of the MAG being used according to the instruction on the readme and not being able to start
![image](https://github.com/swisspost/MobileAccessGateway/assets/8686515/591382a0-5297-4c3a-bce5-ff702ebbef65)

**Comment by lfdesousa** [comment]
I can confirm, that when we do a revert to this commit: 14d6ebb58fe8b11d48ce7f1d7028c0950cd5f741 we have the Mag working again with SSL, without having to change the files to turn the ssl off.

**Comment by lfdesousa** [comment]
After replication, this seems to be related with the configuration and a mismatch in the files that should be read.

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project mobile-access-gateway: An exception occured while executing the Java class. Error creating bean with name 'sslContext' defined in class path resource [ch/bfh/ti/i4mi/mag/Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.camel.support.jsse.SSLContextParameters]: Factory method 'getPixSSLContext' threw exception; nested exception is java.io.FileNotFoundException: src/main/resources/keystore.jks (No such file or directory) -> [Help 1]

**Comment by lfdesousa** [comment]
This is fixed with the commits in the branch: 
https://github.com/swisspost/MobileAccessGateway/commit/fd351f62ebe386c28fd1ccfa7e2001de97edc4aa
https://github.com/swisspost/MobileAccessGateway/commit/67052f81304964f5d831c5a3fc96743fffb4198f
The tests run without errors and the Mag can be executed in standalone with SSL enabled.

**Comment by staffoleo** [comment]
fixed
